
BEGIN;
-- ======================
-- 1) CATÁLOGOS
-- ======================
CREATE TABLE IF NOT EXISTS moneda (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   TEXT   NOT NULL UNIQUE,
  simbolo  TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS pais (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    TEXT   NOT NULL UNIQUE,
  "monedaFK" BIGINT NOT NULL,
  CONSTRAINT fk_pais_moneda
    FOREIGN KEY ("monedaFK")
    REFERENCES moneda(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_pais_monedaFK ON pais("monedaFK");

CREATE TABLE IF NOT EXISTS "catalogoTipoSorteo" (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "metodoPago" (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metodo TEXT NOT NULL UNIQUE
);

-- Relación métodos de pago habilitados por país (+ API usada)
CREATE TABLE IF NOT EXISTS "metodoPagoXPais" (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api            TEXT   NOT NULL,
  "paisFK"       BIGINT NOT NULL,
  "metodoPagoFK" BIGINT NOT NULL,
  CONSTRAINT fk_mp_x_pais__pais
    FOREIGN KEY ("paisFK")
    REFERENCES pais(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_mp_x_pais__metodo
    FOREIGN KEY ("metodoPagoFK")
    REFERENCES "metodoPago"(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  -- En un país, un método de pago no debe repetirse
  CONSTRAINT uq_mp_x_pais UNIQUE ("paisFK","metodoPagoFK")
);
CREATE INDEX IF NOT EXISTS idx_mp_x_pais__paisFK        ON "metodoPagoXPais"("paisFK");
CREATE INDEX IF NOT EXISTS idx_mp_x_pais__metodoPagoFK  ON "metodoPagoXPais"("metodoPagoFK");

-- ======================
-- 2) ENTIDADES
-- ======================

CREATE TABLE IF NOT EXISTS usuario (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   TEXT NOT NULL,
  telefono TEXT NOT NULL,
  "paisFK" BIGINT NOT NULL,
  CONSTRAINT fk_usuario_pais
    FOREIGN KEY ("paisFK")
    REFERENCES pais(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_usuario_paisFK ON usuario("paisFK");

CREATE TABLE IF NOT EXISTS sorteo (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero             INTEGER NOT NULL,            -- número del sorteo (ej. 1001, 1101...)
  "paisFK"           BIGINT  NOT NULL,
  "categoriaSorteoFK" BIGINT NOT NULL,            -- referencia a catalogoTipoSorteo
  "fechaSorteo"      TIMESTAMPTZ NOT NULL,
  CONSTRAINT fk_sorteo_pais
    FOREIGN KEY ("paisFK")
    REFERENCES pais(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_sorteo_categoria
    FOREIGN KEY ("categoriaSorteoFK")
    REFERENCES "catalogoTipoSorteo"(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sorteo_paisFK            ON sorteo("paisFK");
CREATE INDEX IF NOT EXISTS idx_sorteo_categoriaSorteoFK ON sorteo("categoriaSorteoFK");
CREATE INDEX IF NOT EXISTS idx_sorteo_fecha             ON sorteo("fechaSorteo");

-- ======================
-- 3) MOVIMIENTOS ECONÓMICOS
-- ======================

CREATE TABLE IF NOT EXISTS pago (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cantidad              BIGINT NOT NULL,              -- monto pagado
  "metodoPagoXPaisFK"   BIGINT NOT NULL,
  "monedaFK"            BIGINT NOT NULL,
  "usuarioFK"           BIGINT NOT NULL,
  CONSTRAINT fk_pago_metodoPagoXPais
    FOREIGN KEY ("metodoPagoXPaisFK")
    REFERENCES "metodoPagoXPais"(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_pago_moneda
    FOREIGN KEY ("monedaFK")
    REFERENCES moneda(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_pago_usuario
    FOREIGN KEY ("usuarioFK")
    REFERENCES usuario(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_pago_metodoPagoXPaisFK ON pago("metodoPagoXPaisFK");
CREATE INDEX IF NOT EXISTS idx_pago_monedaFK         ON pago("monedaFK");
CREATE INDEX IF NOT EXISTS idx_pago_usuarioFK        ON pago("usuarioFK");

CREATE TABLE IF NOT EXISTS apuesta (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero     INTEGER NOT NULL,      -- 0..9999 (tu inserción lo maneja así)
  monto      BIGINT  NOT NULL,
  "monedaFK" BIGINT  NOT NULL,
  "pagoFK"   BIGINT  NOT NULL,
  "sorteoFK" BIGINT  NOT NULL,
  "usuarioFK" BIGINT NOT NULL,
  CONSTRAINT fk_apuesta_moneda
    FOREIGN KEY ("monedaFK")
    REFERENCES moneda(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_apuesta_pago
    FOREIGN KEY ("pagoFK")
    REFERENCES pago(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_apuesta_sorteo
    FOREIGN KEY ("sorteoFK")
    REFERENCES sorteo(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  CONSTRAINT fk_apuesta_usuario
    FOREIGN KEY ("usuarioFK")
    REFERENCES usuario(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_apuesta_monedaFK  ON apuesta("monedaFK");
CREATE INDEX IF NOT EXISTS idx_apuesta_pagoFK    ON apuesta("pagoFK");
CREATE INDEX IF NOT EXISTS idx_apuesta_sorteoFK  ON apuesta("sorteoFK");
CREATE INDEX IF NOT EXISTS idx_apuesta_usuarioFK ON apuesta("usuarioFK");

COMMIT;
